### ISSUE TITLE
Sharing package on conda and using from terminal R (as opposed to RStudio)

### ISSUE THREAD

**Issue by lc5415** [r-lib/devtools#2206]
Hello,

I have recently created a small package ([https://github.com/lc5415/HDATDS](https://github.com/lc5415/HDATDS)) and hosted it in conda (creating custom conda-recipe and so forth - [https://anaconda.org/lucha6/r-hdatds](https://anaconda.org/lucha6/r-hdatds)). 

Installing the package from RStudio works fine but when I install from conda (`conda install -c lucha6 r-hdatds`), open an R session from the terminal and run `installed.packages()` I cannot see my package listed.

__Reproducible example__
In terminal:
```
conda create -n testPackage
conda activate testPackage
conda install -c lucha6 r-hdatds

#open R session
R
#within R
installed.packages() #list installed packages 
```

I would expect to see a package called HDATDS (in capital letters) but I see no sign of it. Perhaps there is something wrong with my `meta.yaml` file:
<details><summary>Show meta.yaml file</summary>
<p>

```

package:
  name: r-hdatds
  version: 0.1.1

source:
  git_url: https://github.com/lc5415/HDATDS.git

requirements:
    - r-base
  run:
    - r-base
    - r-dplyr
    - r-ROCR
    - r-tidyr
    - r-e1071
    - r-glmnet
    - r-xgboost

about:
  # user-oriented info to be displayed in anaconda.org
  home: https://github.com/lc5415/HDATDS
  license: MIT
  summary: This package was developed as a learning exercise and also to share
   useful functions for the Computational Epidemiology and Translational Data Sciences
   with my colleagues from the MSc in Health Data Analytics & Machine Learning
  license_family: MIT
```
</p></details>

I believe that if I run `devtools::install_github("lc5415/HDATDS")` from an R session from the terminal , the package is kept in future sessions but ideally the package should be automatically available from the conda installation.
